name: Bug report
description: Report a problem with software, documentation, or tests.
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide steps or logs.
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: Environment
      description: Hardware/software versions.
