name: Feature request
description: Request a new feature.
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem statement
      description: What need does this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
  - type: textarea
    attributes:
      label: Safety considerations
