name: Research task
description: Track a research item or validation task.
title: "[Research] "
labels: [research]
body:
  - type: textarea
    attributes:
      label: Research question
      description: What is the specific question?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected output
  - type: textarea
    attributes:
      label: Sources
      description: Add CITATION-TODO where needed.
